[package]
name = "rustupscheck"
version = "0.5.4"
authors = ["Valeriy Kostikov <mkoctuk@gmail.com>"]
edition = "2018"

[dependencies]
native-tls = "0.2"
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
regex = "1.1"

[dependencies.chrono]
version = "0.4"
features = [ "serde" ]